const $=s=>document.querySelector(s);
const API_URL="https://vzbaezoeqjwqlxgczzwu.supabase.co/functions/v1/return-api";
const API_KEY="sb_publishable_82Kj45x7OAaymPKDkOQUpg_s6HpdN06";
const storeNames={master:"master",ret:"ret",archive:"archive",service:"service"};
let master=new Map(),rets=[],archives=[],services=[],cur=null,jenis="",pend=null;
const archiveOpen=new Set(),serviceOpen=new Set();let archiveExportOpen="";
function toast(t){const e=$("#toast");if(e){e.textContent=t;e.classList.add("on");clearTimeout(toast.h);toast.h=setTimeout(()=>e.classList.remove("on"),3000)}}
function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function fmt(ts){const d=new Date(ts);if(Number.isNaN(d.getTime()))return{tgl:"-",jam:"-"};return{tgl:d.toLocaleDateString("id-ID",{day:"2-digit",month:"2-digit",year:"numeric"}),jam:d.toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).replace(/\./g,":")}}
function dkey(ts){const d=new Date(ts);if(Number.isNaN(d.getTime()))return "";return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function normalizeReturn(r){return {...r,jumlah:Number(r.jumlah)||1,status:r.status||"Belum Diambil",ket:r.ket||""}}
async function api(action,store,data,id){const body={action,store};if(data!==undefined)body.data=data;if(id!==undefined)body.id=id;const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json","apikey":API_KEY,"Authorization":"Bearer "+API_KEY},body:JSON.stringify(body)});let out={};try{out=await res.json()}catch{}if(!res.ok||out.error)throw new Error(out.error||`HTTP ${res.status}`);return out}
async function getAll(store){
  const result = await api("list", storeNames[store]);
  return result.rows || [];
}
async function insertRow(store,row){return (await api("insert",storeNames[store],row)).row}
async function updateRow(store,row){return (await api("update",storeNames[store],row,row.id)).row}
async function deleteRow(store,id){return api("delete",storeNames[store],undefined,id)}
function setRows(m,r,a,s){master=new Map();for(const x of m){if(x.key!==undefined)master.set(String(x.key),x);if(x.kode!==undefined)master.set(String(x.kode),x);if(x.barcode)master.set(String(x.barcode),x)}rets=r.map(normalizeReturn);archives=a.map(normalizeReturn);services=s}
async function refreshAll(){const [m,r,a,s]=await Promise.all([getAll("master"),getAll("ret"),getAll("archive"),getAll("service")]);setRows(m,r,a,s);render();renderArchive();renderMasterCount();renderService()}
function initTabs(){document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.setAttribute("aria-selected",x===b));["input","data","archive","master","service"].forEach(t=>$("#t-"+t).classList.toggle("hide",t!==b.dataset.t));if(b.dataset.t==="data")render();if(b.dataset.t==="archive")renderArchive();if(b.dataset.t==="master")renderMasterCount();if(b.dataset.t==="service")renderService();if(b.dataset.t==="input")$("#scan").focus()})}
async function init(){initTabs();try{await refreshAll();await rollover();toast("Terhubung ke Supabase")}catch(e){console.error(e);toast("Gagal memuat Supabase: "+e.message)}$("#scan").focus();setInterval(async()=>{try{await refreshAll();await rollover()}catch(e){console.error("refresh",e)}},60000)}
function lookup(){const v=$("#scan").value.trim(),box=$("#item"),sug=$("#suggestions");if(!v){cur=null;sug.classList.add("hide");sug.innerHTML="";box.className="item";box.innerHTML='<span class="k">Barang akan tampil di sini setelah kode di-scan atau dipilih dari pencarian.</span>';upd();return}cur=master.get(v)||master.get(v.toUpperCase())||null;if(cur){sug.classList.add("hide");sug.innerHTML="";box.className="item";box.innerHTML='<div class="k">Kode '+esc(cur.kode)+'</div><div class="n">'+esc(cur.nama)+'</div>'}else{const q=v.toLowerCase(),found=[],seen=new Set();for(const x of master.values()){const kode=String(x.kode||""),nama=String(x.nama||""),k=kode+"|"+nama;if(!seen.has(k)&&(kode+" "+nama).toLowerCase().includes(q)){seen.add(k);found.push(x)}if(found.length>=12)break}sug.innerHTML=found.map(x=>'<button type="button" class="suggest" data-k="'+esc(x.key||x.kode)+'"><strong>'+esc(x.nama)+'</strong><span>'+esc(x.kode)+'</span></button>').join("");sug.classList.toggle("hide",!found.length);box.className="item bad";box.innerHTML=master.size?'<div class="n">Pilih barang dari hasil pencarian</div>':'<div class="n">Master barang masih kosong</div><div class="k">Import file Excel di tab Master Barang.</div>'}upd()}
function getJumlah(){const n=parseInt($("#jumlah").value,10);return Number.isFinite(n)&&n>=1?n:0}function upd(){$("#simpan").disabled=!(cur&&jenis&&getJumlah()>=1)}
$("#scan").addEventListener("input",lookup);$("#scan").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();lookup();if(cur)$("#jumlah").focus()}});$("#suggestions").onclick=e=>{const b=e.target.closest("[data-k]");if(!b)return;const x=master.get(b.dataset.k);if(!x)return;cur=x;$("#scan").value=x.kode;lookup();$("#jumlah").focus()};$("#jumlah").addEventListener("input",upd);$("#jumlah").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();$("#ket").focus()}});$("#ket").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();simpan()}});document.querySelectorAll(".seg button").forEach(b=>b.onclick=()=>{jenis=b.dataset.j;document.querySelectorAll(".seg button").forEach(x=>x.setAttribute("aria-pressed",x===b));upd()});$("#simpan").onclick=simpan;
async function simpan(){if(!cur||!jenis)return;const jumlah=getJumlah();if(!jumlah){toast("Jumlah minimal 1");return}try{const r=await insertRow("ret",{ts:new Date().toISOString(),kode:cur.kode,nama:cur.nama,jumlah,jenis,status:"Belum Diambil",ket:$("#ket").value.trim()});rets.push(r);$("#scan").value="";$("#jumlah").value="1";$("#ket").value="";lookup();render();toast("Return tersimpan")}catch(e){console.error(e);toast("Gagal menyimpan Return: "+e.message)}}
function render(){const q=$("#cari").value.trim().toLowerCase(),fj=$("#fj").value,list=rets.filter(r=>(!fj||r.jenis===fj)&&(!q||(String(r.kode)+" "+String(r.nama)+" "+String(r.ket)).toLowerCase().includes(q))).sort((a,b)=>String(b.ts).localeCompare(String(a.ts))),show=list.slice(0,300);$("#cnt").textContent=list.length?list.length+" data"+(list.length>show.length?", menampilkan 300 terbaru.":""):"Belum ada data Return.";$("#tb").innerHTML=show.map(r=>{const f=fmt(r.ts),st=r.status||"Belum Diambil";return '<tr><td>'+f.tgl+'</td><td>'+f.jam+'</td><td>'+esc(r.kode)+'</td><td>'+esc(r.nama)+'</td><td>'+Number(r.jumlah||1)+'</td><td>'+esc(r.jenis)+'</td><td><button class="check '+(st==="Sudah Diambil"?"done":"")+'" data-check="'+r.id+'">'+(st==="Sudah Diambil"?"✓ Sudah Diambil":"☐ Belum Diambil")+'</button></td><td>'+esc(r.ket)+'</td><td><button class="x" data-d="'+r.id+'">Hapus</button></td></tr>'}).join("")}
$("#cari").oninput=render;$("#fj").onchange=render;$("#tb").onclick=async e=>{const c=e.target.closest("[data-check]");if(c){const r=rets.find(x=>+x.id===+c.dataset.check);if(!r||r.status==="Sudah Diambil")return;r.status="Sudah Diambil";try{await updateRow("ret",r);render();toast("Status diperbarui")}catch(err){toast("Gagal update: "+err.message)}return}const b=e.target.closest("[data-d]");if(!b)return;if(!confirm("Hapus data Return ini?"))return;try{await deleteRow("ret",+b.dataset.d);rets=rets.filter(x=>+x.id!==+b.dataset.d);render();toast("Return dihapus")}catch(err){toast("Gagal menghapus: "+err.message)}};
async function rollover(){const today=dkey(new Date());const rows=rets.filter(r=>dkey(r.ts)&&dkey(r.ts)<today);if(!rows.length)return;try{for(const r of rows){const cp={...r,originalId:r.id,archivedAt:new Date().toISOString()};delete cp.id;await insertRow("archive",cp);await deleteRow("ret",r.id)}const ids=new Set(rows.map(x=>+x.id));rets=rets.filter(x=>!ids.has(+x.id));archives=await getAll("archive");render();renderArchive();toast(rows.length+" data dipindahkan ke Arsip")}catch(e){console.error(e);toast("Arsip gagal diproses; periksa koneksi")}}
function archiveDayLabel(k){const [y,m,d]=k.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString("id-ID",{weekday:"long",day:"2-digit",month:"long",year:"numeric"})}function groupedByDay(rows){const g=new Map();[...rows].sort((a,b)=>String(b.ts).localeCompare(String(a.ts))).forEach(r=>{const k=dkey(r.ts)||"tanpa-tanggal";if(!g.has(k))g.set(k,[]);g.get(k).push(r)});return g}
function downloadXlsx(aoa,sheet,name,widths){if(!window.XLSX){toast("Library Excel belum dimuat");return}const ws=XLSX.utils.aoa_to_sheet(aoa);if(widths)ws["!cols"]=widths.map(w=>({wch:w}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheet);const blob=new Blob([XLSX.write(wb,{bookType:"xlsx",type:"array"})],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportReturns(rows,name){if(!rows.length){toast("Tidak ada data untuk diexport");return}downloadXlsx([["Tanggal","Jam","Kode Barang","Nama Barang","Jumlah","Jenis Return","Keterangan"],...rows.map(r=>{const f=fmt(r.ts);return[f.tgl,f.jam,String(r.kode),r.nama,+r.jumlah||1,r.jenis,r.ket||""]})],"Return",name,[12,10,16,44,10,22,50])}async function exportXlsx(j,name){exportReturns(rets.filter(r=>r.jenis===j),name)}$("#exP").onclick=()=>exportXlsx("Pecah Belah","EXPORT RETURN PECAH BELAH.xlsx");$("#exB").onclick=()=>exportXlsx("Bukan Pecah Belah","EXPORT RETURN BUKAN PECAH BELAH.xlsx");
function renderArchive(){const groups=groupedByDay(archives);$("#arcCnt").textContent=archives.length?archives.length+" data arsip dalam "+groups.size+" hari":"Belum ada arsip Return.";let html="";for(const [key,list] of groups){const open=archiveOpen.has(key),exOpen=archiveExportOpen===key;html+='<div class="archive-folder card"><div class="folder-head"><div><strong>'+esc(archiveDayLabel(key))+'</strong><div class="note">'+list.length+' data Return</div></div><div class="folder-actions"><button class="btn alt" data-open-archive="'+esc(key)+'">'+(open?"Tutup":"Lihat")+'</button><button class="btn" data-toggle-archive-export="'+esc(key)+'">Export</button></div></div>'+(exOpen?'<div class="export-choice"><button class="btn" data-export-archive-type="Pecah Belah" data-export-archive="'+esc(key)+'">Pecah Belah</button><button class="btn alt" data-export-archive-type="Bukan Pecah Belah" data-export-archive="'+esc(key)+'">Bukan Pecah Belah</button></div>':"")+'<div class="folder-body '+(open?"":"hide")+'"><div class="tw"><table><thead><tr><th>Tanggal</th><th>Jam</th><th>Kode</th><th>Nama</th><th>Jumlah</th><th>Jenis</th><th>Status</th><th>Keterangan</th><th>Aksi</th></tr></thead><tbody>'+list.map(r=>{const f=fmt(r.ts);return '<tr><td>'+f.tgl+'</td><td>'+f.jam+'</td><td>'+esc(r.kode)+'</td><td>'+esc(r.nama)+'</td><td>'+r.jumlah+'</td><td>'+esc(r.jenis)+'</td><td>'+esc(r.status)+'</td><td>'+esc(r.ket)+'</td><td><button class="x" data-ad="'+r.id+'">Hapus</button></td></tr>'}).join("")+'</tbody></table></div></div></div>'}$("#ta").innerHTML=html||'<div class="card"><p class="note">Belum ada arsip Return.</p></div>'}
$("#ta").onclick=async e=>{const op=e.target.closest("[data-open-archive]");if(op){const k=op.dataset.openArchive;archiveOpen.has(k)?archiveOpen.delete(k):archiveOpen.add(k);renderArchive();return}const tg=e.target.closest("[data-toggle-archive-export]");if(tg){archiveExportOpen=archiveExportOpen===tg.dataset.toggleArchiveExport?"":tg.dataset.toggleArchiveExport;renderArchive();return}const ex=e.target.closest("[data-export-archive-type]");if(ex){const k=ex.dataset.exportArchive,j=ex.dataset.exportArchiveType;exportReturns(archives.filter(r=>(dkey(r.ts)||"tanpa-tanggal")===k&&r.jenis===j),"ARSIP RETURN "+k+" - "+j.toUpperCase()+".xlsx");return}const b=e.target.closest("[data-ad]");if(!b)return;if(!confirm("Hapus arsip ini?"))return;try{await deleteRow("archive",+b.dataset.ad);archives=archives.filter(x=>+x.id!==+b.dataset.ad);renderArchive()}catch(err){toast("Gagal hapus arsip: "+err.message)}};
$("#clearA").onclick=async()=>{if(!archives.length||!confirm("Hapus semua arsip? Tidak bisa dibatalkan."))return;try{for(const r of [...archives])await deleteRow("archive",r.id);archives=[];renderArchive();toast("Arsip dikosongkan")}catch(e){toast("Gagal menghapus arsip: "+e.message)}};
function renderMasterCount(){const e=$("#masterCount");if(e)e.textContent="Jumlah Master Barang: "+new Set([...master.values()].map(x=>String(x.kode))).size.toLocaleString("id-ID")+" data"}
$("#file").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(!window.XLSX)throw Error("Library Excel tidak termuat; periksa koneksi internet");const wb=XLSX.read(await f.arrayBuffer(),{type:"array"}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,raw:true,defval:""});const h=rows.findIndex(r=>r.some(c=>String(c).trim()!==""));if(h<0)throw Error("File kosong");pend={rows:rows.slice(h+1),head:rows[h].map((c,i)=>String(c).trim()||"Kolom "+(i+1))};const opt=none=>(none?'<option value="-1">Tidak dipakai</option>':"")+pend.head.map((c,i)=>'<option value="'+i+'">'+esc(c)+'</option>').join("");$("#mk").innerHTML=opt(false);$("#mnm").innerHTML=opt(false);$("#mb").innerHTML=opt(true);const find=(re,exclude=-1)=>pend.head.findIndex((c,i)=>re.test(c)&&i!==exclude),n=find(/nama|name|deskripsi/i),k=find(/kode|code|plu|sku/i,n),b=find(/barcode|bar code/i);$("#mnm").value=n>=0?n:Math.min(1,pend.head.length-1);$("#mk").value=k>=0?k:0;$("#mb").value=b>=0?b:-1;$("#mInfo").textContent=pend.rows.length+" baris terbaca. Pastikan kolom benar sebelum impor.";$("#map").classList.remove("hide");toast("File terbaca; periksa pemetaan kolom") }catch(err){console.error(err);toast("Gagal membaca Excel: "+err.message)}};
/* Import master dibuat non-destruktif: hanya menambahkan kode baru atau memperbarui kode sama. Tidak pernah clear tabel. */
$("#imp").onclick=async()=>{if(!pend)return toast("Pilih file Excel dahulu");const ik=+$("#mk").value,inm=+$("#mnm").value,ib=+$("#mb").value;if(ik<0||inm<0)return toast("Kolom kode dan nama wajib dipilih");const m=new Map();for(const row of pend.rows){const kode=String(row[ik]??"").trim(),nama=String(row[inm]??"").trim();if(!kode||!nama)continue;const barcode=ib>=0?String(row[ib]??"").trim():"";m.set(kode,{key:kode,kode,nama,...(barcode?{barcode}:{})})}const arr=[...m.values()];if(!arr.length)return toast("Tidak ada baris valid; cek pilihan kolom");const btn=$("#imp");btn.disabled=true;btn.textContent="Mengimpor...";let ok=0,fail=0;try{const existing=await getAll("master"),byCode=new Map(existing.map(x=>[String(x.kode),x]));for(let i=0;i<arr.length;i++){const row=arr[i];try{if(byCode.has(row.kode)){const old=byCode.get(row.kode);await updateRow("master",{...old,...row,id:old.id});}else{await insertRow("master",row)}ok++}catch(e){fail++;console.error("Import baris gagal",row.kode,e)}if((i+1)%100===0){btn.textContent=`Mengimpor ${i+1}/${arr.length}...`;}}await refreshAll();pend=null;$("#map").classList.add("hide");$("#file").value="";lookup();toast(`Impor selesai: ${ok} berhasil, ${fail} gagal. Data lama tidak dikosongkan.`)}catch(e){console.error(e);toast("Impor gagal: "+e.message+". Data lama tidak dihapus.")}finally{btn.disabled=false;btn.textContent="Import Master Barang"}};
function serviceDayLabel(k){return k==="tanpa-tanggal"?"Tanpa Tanggal":archiveDayLabel(k)}function renderService(){const groups=groupedByDay(services);$("#serviceCnt").textContent=services.length?services.length+" data Service dalam "+groups.size+" hari":"Belum ada data Service.";let html="";for(const [k,list] of groups){const open=serviceOpen.has(k);html+='<div class="service-folder card"><div class="folder-head"><div><strong>'+esc(serviceDayLabel(k))+'</strong><div class="note">'+list.length+' data Service</div></div><div class="folder-actions"><button class="btn alt" data-open-service="'+esc(k)+'">'+(open?"Tutup":"Lihat")+'</button><button class="btn" data-export-service="'+esc(k)+'">Export</button></div></div><div class="folder-body '+(open?"":"hide")+'"><div class="tw"><table><thead><tr><th>Tanggal</th><th>Jam</th><th>Nama</th><th>Nomor HP</th><th>Nama Barang</th><th>Kode</th><th>Kendala</th><th>Keterangan</th><th>Aksi</th></tr></thead><tbody>'+list.map(r=>{const f=fmt(r.ts);return '<tr><td>'+f.tgl+'</td><td>'+f.jam+'</td><td>'+esc(r.nama)+'</td><td>'+esc(r.hp)+'</td><td>'+esc(r.barang)+'</td><td>'+esc(r.kode)+'</td><td>'+esc(r.kendala)+'</td><td>'+esc(r.ket)+'</td><td><button class="check done" data-sv-taken="'+r.id+'">Sudah Diambil</button> <button class="x" data-sd="'+r.id+'">Hapus</button></td></tr>'}).join("")+'</tbody></table></div></div></div>'}$("#ts").innerHTML=html||'<p class="note">Belum ada data Service.</p>'}
$("#simpanService").onclick=async()=>{const r={ts:new Date().toISOString(),nama:$("#svNama").value.trim(),hp:$("#svHp").value.trim(),barang:$("#svBarang").value.trim(),kode:$("#svKode").value.trim(),kendala:$("#svKendala").value.trim(),ket:$("#svKet").value.trim()};if(!r.nama||!r.hp||!r.barang||!r.kendala)return toast("Nama, nomor HP, barang, dan kendala wajib diisi");try{services.push(await insertRow("service",r));["svNama","svHp","svBarang","svKode","svKendala","svKet"].forEach(id=>$("#"+id).value="");renderService();toast("Service tersimpan")}catch(e){toast("Gagal simpan Service: "+e.message)}};
$("#ts").onclick=async e=>{const op=e.target.closest("[data-open-service]");if(op){const k=op.dataset.openService;serviceOpen.has(k)?serviceOpen.delete(k):serviceOpen.add(k);renderService();return}const ex=e.target.closest("[data-export-service]");if(ex){const k=ex.dataset.exportService,rows=services.filter(r=>(dkey(r.ts)||"tanpa-tanggal")===k);downloadXlsx([["Tanggal","Jam","Nama","Nomor HP","Nama Barang","Kode","Kendala","Keterangan"],...rows.map(r=>{const f=fmt(r.ts);return[f.tgl,f.jam,r.nama,r.hp,r.barang,r.kode,r.kendala,r.ket]})],"Service","SERVICE "+k+".xlsx",[12,10,24,18,32,18,36,36]);return}const taken=e.target.closest("[data-sv-taken]"),del=e.target.closest("[data-sd]");if(!taken&&!del)return;const id=+(taken?taken.dataset.svTaken:del.dataset.sd);if(!confirm(taken?"Tandai sudah diambil dan hapus dari daftar Service?":"Hapus data Service?"))return;try{await deleteRow("service",id);services=services.filter(r=>+r.id!==id);renderService();toast("Data Service dihapus")}catch(err){toast("Gagal: "+err.message)}};
init();
